spring:
  application:
    name: SmokeFreeBot
  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/smoke-free-bot}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      auto-commit: false
  jpa:
    show-sql: ${SHOW_SQL:true}
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: ${POSTGRES_SCHEMA:main}
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    default-schema: ${POSTGRES_SCHEMA:main}
    change-log: classpath:/db/changelog/master.yml
    database-change-log-table: _databasechangelog
    database-change-log-lock-table: _databasechangeloglock

custom:
  bot:
    name: "SmokeFreeBot"
    token: ${BOT_TOKEN}
